version: '3.8'
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8090:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_PORT: 3310s4
  mysqldb:
    build:
      context: .
      dockerfile: Dockerfile-bd
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: devopsprojet
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin
    restart: always
    ports:
      - 8091:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password




#version: '3.8'
#
#services:
#  mysqldb:
#  app:
#volumes: